dist: xenial
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - pip install pep8
script:
  - find . -name \*.py -exec pep8 --ignore=E501 {} +
  - ./setup.py install
